---
- hosts: push_nginxs
  remote_user: root
#  become: yes
#  become_user: root
#  become_method: sudo
  roles:
    - ansible-yum-nginx
#    - nginx
#    - nginx_site
#    - lets_encrypt
#    - s3_sync
#    - logrotate
#

