---
# tasks file for ansible-java-oracle-jdk
- name: copy rpm file to vm
  copy:
    src: jdk-8u172-linux-x64.rpm
    dest: /tmp
    owner: root
    group: root
    mode: 0644


- name: install oracle jdk rpm from a local file
  yum:
    name: /tmp/jdk-8u172-linux-x64.rpm
    state: present
